create table if not exists public.public_address_access_logs (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  username text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.public_address_blocks (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  blocked_until timestamptz not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists public_address_access_logs_ip_hash_created_at_idx
on public.public_address_access_logs (ip_hash, created_at desc);

create index if not exists public_address_blocks_ip_hash_blocked_until_idx
on public.public_address_blocks (ip_hash, blocked_until desc);

alter table public.public_address_access_logs enable row level security;
alter table public.public_address_blocks enable row level security;
